Repository openshift/security-profiles-operator, pull requests merged in 2025-08, with the labels that each got.

#90 OCPBUGS-60048: Fixing profile recording
  internal/pkg/webhooks/recording/recording.go
Labels: lgtm, approved, jira/invalid-bug, jira/severity-important, jira/valid-reference

#92 OCPBUGS-60139: Fix selinux profilerecording
  internal/pkg/webhooks/recording/recording.go
Labels: approved, jira/invalid-bug, jira/severity-important, jira/valid-reference

#93 Update bundle references for rpms-signature-scan
  .tekton/security-profiles-operator-bundle-dev-pull-request.yaml
  .tekton/security-profiles-operator-bundle-dev-push.yaml
  .tekton/security-profiles-operator-bundle-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-bundle-release-0-9-push.yaml
  .tekton/security-profiles-operator-dev-pull-request.yaml
  .tekton/security-profiles-operator-dev-push.yaml
  .tekton/security-profiles-operator-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-release-0-9-push.yaml
Labels: approved

#96 Update security profiles operator image reference in update_csv.go
  bundle-hack/update_csv.go
Labels: lgtm, qe-approved, approved

#98 switch to tekton-catalog for rpms-signature-scan task
  .tekton/security-profiles-operator-bundle-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-bundle-release-0-9-push.yaml
  .tekton/security-profiles-operator-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-release-0-9-push.yaml
Labels: approved

#99 Update image reference
  bundle-hack/update_csv.go
Labels: approved
