Repository openshift/security-profiles-operator, pull requests merged in 2025-07, with the labels that each got.

#78 Setup release-0.9 branch and add release pipeline configs
  .tekton/security-profiles-operator-bundle-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-bundle-release-0-9-push.yaml
  .tekton/security-profiles-operator-release-0-9-pull-request.yaml
  .tekton/security-profiles-operator-release-0-9-push.yaml
  bundle-hack/update_csv.go
Labels: approved

#79 Release 0.9 Update
  bundle-hack/update_csv.go
Labels: approved

#86 Add support for PPC64LE architecture in security profiles operator
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  examples/seccompprofile.yaml
Labels: kind/feature, lgtm, approved

#87 Sync SPO image ref
  bundle-hack/update_csv.go
Labels: approved

#88 Fix empty version label in bundle image
  bundle.openshift.Dockerfile
Labels: kind/bug, approved
